spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zht?userUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=UTC
    username: root
    password: 123